workflows:
  ios-testflight:
    integrations:
      app_store_connect: "app store connect"
    environment:
      flutter: 3.47.5
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.fcwe1113.busArrivalNotificationApp.66RCG95DR7
    scripts:
      - name: Generate secrets configuration
        script: |
          mkdir -p config
          echo "$SECRETS_JSON" | base64 --decode > config/secrets.json
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install pods
        script: cd ios && pod install
      - name: Apply signing
        script: xcode-project use-profiles
      - name: Build ipa
        script: |
          flutter build ipa --release \
            --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist --archive-flags="-destination 'generic/platform=iOS'"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
    
