// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH398_yTGfmF_5fNHX1B7oSuHXF46ND-w',
    appId: '1:27407470668:web:536b6316ddfaa908dee4e9',
    messagingSenderId: '27407470668',
    projectId: 'transport-alarm',
    authDomain: 'transport-alarm.firebaseapp.com',
    storageBucket: 'transport-alarm.firebasestorage.app',
    measurementId: 'G-Q16JGN2R47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpgIni0CWFs-ZnRNKtkHSWKm-rXqF8IOs',
    appId: '1:27407470668:android:c83bc59cd34e0134dee4e9',
    messagingSenderId: '27407470668',
    projectId: 'transport-alarm',
    storageBucket: 'transport-alarm.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzq5tgMOe4xV6ayEfG_JQ-yM21OglJYHA',
    appId: '1:27407470668:ios:1c98e80ddf5d808bdee4e9',
    messagingSenderId: '27407470668',
    projectId: 'transport-alarm',
    storageBucket: 'transport-alarm.firebasestorage.app',
    iosBundleId: 'com.fcwe1113.busArrivalNotificationApp.66RCG95DR7',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzq5tgMOe4xV6ayEfG_JQ-yM21OglJYHA',
    appId: '1:27407470668:ios:f87264e8effe2e47dee4e9',
    messagingSenderId: '27407470668',
    projectId: 'transport-alarm',
    storageBucket: 'transport-alarm.firebasestorage.app',
    iosBundleId: 'com.fcwe1113.busArrivalNotificationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH398_yTGfmF_5fNHX1B7oSuHXF46ND-w',
    appId: '1:27407470668:web:6199e7ca34fd82c6dee4e9',
    messagingSenderId: '27407470668',
    projectId: 'transport-alarm',
    authDomain: 'transport-alarm.firebaseapp.com',
    storageBucket: 'transport-alarm.firebasestorage.app',
    measurementId: 'G-GK0XKJ6TT1',
  );
}
